#!/usr/bin/env python3
from pathlib import Path
import html
import re

import build_seo as seo

PUBLIC = seo.PUBLIC
BASE = seo.BASE
LOCALES = ('zh', 'ja', 'ru', 'es', 'pt')
LANG = {'zh': 'zh-CN', 'ja': 'ja', 'ru': 'ru', 'es': 'es', 'pt': 'pt'}

COPY = {
'zh': {
 'brand_sub':'中国采购与供应链执行','services':'服务','cases':'案例','about':'关于','resources':'资源','contact':'提交需求','direct':'直接联系',
 'services_page':{
  'title':'中国采购服务｜供应商开发、OEM/ODM、验货与出口｜Pomerol International','desc':'面向海外买方的中国采购执行服务：需求工程、供应商开发、询价比价、OEM/ODM、样品、验厂验货、集货与出口协调。','eyebrow':'中国采购服务','h1':'从“帮我找工厂”，做到可下单、可验收、可出货。','intro':'可单独使用某个模块，也可以把中国侧采购执行整体交给我们。项目开始前明确范围、责任、商业条件和需要另行支付的第三方费用。','modules_title':'八个模块，一条可追踪的采购链。','modules_intro':'把寻源、技术确认、样品、质量和物流拆开管理，才能让成本、风险和责任始终可见。',
  'modules':[('需求工程','把照片、图纸、BOM、参考链接或初步想法整理成可询价的采购规格。'),('供应商开发与筛选','从产业带、B2B平台和品类渠道寻找候选方，先排除能力不匹配。'),('RFQ标准化','把模具、MOQ、单价、包装、付款、交期、质保和排除项放到同一口径比较。'),('样品与DFM跟进','记录样品版本、技术反馈和偏差，量产放行前关闭关键问题。'),('供应商资格核查','核对主体、工厂证据、相关认证和实际制程能力。'),('质量控制','依据图纸、批准样、AQL或项目标准设定过程与出货前检查点。'),('集货与出口文件','协调多供应商到货、装箱单、唛头、商业文件和货代交接。'),('长期中国采购台','适合持续RFQ、复购、供应商跟进、替代料与异常处理。')],
  'commercial':'合作方式','commercial_intro':'具体费用取决于品类复杂度、供应商数量、差旅、检验深度和交易结构。','models':[('固定项目费','适合明确的一次性任务：短名单、报价比较、样品阶段或单次出货。'),('采购服务费','适合由我们持续管理下单、QC、集货和出口执行。'),('月度中国采购台','适合长期有询价、复购、供应商沟通和中国本地协调需求的公司。')], 'cta':'讨论你的采购项目 →'
 },
 'about_page':{
  'title':'关于 Pomerol International｜珠海中国采购执行团队','desc':'Pomerol International 位于广东珠海，为海外买方提供中国供应商开发、采购执行、质量控制、OEM/ODM和出口协调。','eyebrow':'关于我们','h1':'海外买方的中国侧采购执行端。','intro':'Pomerol International（波美猴国际贸易（珠海）有限公司）立足广东珠海。我们的角色不是简单转发工厂链接，而是把需求、报价、样品、质量节点和交付资料整理成可决策、可追踪的采购流程。','principles_title':'我们如何工作','principles':[('先定义需求','先把规格、版本、数量、市场和验收条件讲清楚，再扩大供应商搜索。'),('证据替代口头承诺','主体、能力、认证、样品、测试、检验和文件尽量留下可复核记录。'),('把偏差显性化','价格低并不自动等于更优；MOQ、模具、材料、包装、交期和排除项必须同时比较。'),('交付不是“工厂做完”','直到检验、集货、文件、包装和货代交接准备完成，采购任务才真正接近结束。')],
  'location_title':'珠海 · 广东 · 中国','location':'珠海位于粤港澳大湾区，连接珠三角制造业集群。我们可以围绕项目在广东及中国其他产业带开展供应商开发与执行协调。','transparency':'案例中的客户名称和部分商业细节采用化名或示例化处理；图库照片用于展示相关真实品类和采购场景，不作为某个化名客户真实出货的证明。'
 },
 'resources_page':{
  'title':'中国采购模板与买方工具箱｜Pomerol International','desc':'免费下载RFQ、供应商评分、验厂、样品批准、出货前验货、包装、采购订单和到岸成本等中国采购模板。','eyebrow':'买方工具箱','h1':'八份可以直接拿来管理中国采购项目的工作表。','intro':'这些模板用于把聊天记录和截图里的信息转成结构化记录。可自己使用，也可以把已有资料发给我们，再按同一采购口径重建。','toolkit':'采购控制模板','guides':'采购指南','guides_desc':'进一步阅读供应商核查、RFQ、样品批准、验货、集货、OEM/ODM和采购成本等深度指南。'
 },
 'contact_page':{
  'title':'联系 Pomerol International｜提交中国采购需求','desc':'向 Yusuf 提交产品、图纸、BOM、数量、目标市场和时间要求，开始中国供应商开发、OEM/ODM、质量与出口执行。','eyebrow':'提交采购需求','h1':'先把你已经有的资料发过来，不需要整理得很完美。','intro':'产品链接、照片、图纸、BOM、旧报价、样品问题或供应商名单都可以作为起点。我们先判断缺少哪些决策信息，再确定下一步。','prep':'最好包含这些信息','prep_items':['产品/品类与关键规格','预计数量、目标价格或预算区间（如有）','目标市场及认证/合规要求','期望样品、量产或出货时间'],'form_title':'建立采购简报','name':'姓名','company':'公司','email':'邮箱','market':'国家 / 市场','product':'产品 / 品类','quantity':'预计数量','timing':'目标时间','message':'补充说明','submit':'生成邮件并发送给 Yusuf →'
 }
},
'ja': {
 'brand_sub':'中国調達・購買実行','services':'サービス','cases':'事例','about':'会社情報','resources':'資料','contact':'RFQを開始','direct':'直接連絡',
 'services_page':{'title':'中国調達サービス｜サプライヤー開拓・OEM/ODM・検品・輸出｜Pomerol International','desc':'海外バイヤー向け中国調達実行支援。要件整理、サプライヤー開拓、RFQ比較、OEM/ODM、サンプル、工場確認、検品、集約・輸出調整。','eyebrow':'中国調達サービス','h1':'「工場を探す」から、発注・検証・出荷可能な状態まで。','intro':'単一モジュールでも、中国側の調達デスクとして一括でも利用できます。開始前に範囲、責任、商条件、第三者費用を明確にします。','modules_title':'8つのサービスを1つの管理可能なワークフローへ。','modules_intro':'探索、技術確認、サンプル、品質、物流を分けて管理し、コスト・リスク・責任を見える化します。','modules':[('要件整理','写真、図面、BOM、参考URLやラフなアイデアを、見積可能な調達仕様へ変換します。'),('サプライヤー開拓・選別','産業集積地、B2Bプラットフォーム、専門チャネルから候補を探し、能力不一致を早期に除外します。'),('RFQ標準化','金型、MOQ、価格、包装、支払、納期、保証、除外条件を同じ基準で比較します。'),('サンプル・DFMフォロー','サンプル改訂、技術フィードバック、逸脱を記録し、量産前に重要事項を閉じます。'),('サプライヤー適格性確認','法人情報、工場証拠、関連認証、工程能力を確認します。'),('品質管理','図面、承認サンプル、AQLまたは案件固有基準に基づき工程・出荷前チェックを定義します。'),('集約・輸出書類','複数工場の納品、パッキングリスト、シッピングマーク、商業書類、フォワーダー引渡しを調整します。'),('継続中国購買デスク','継続RFQ、リピート発注、代替先、例外対応を中国側で管理します。')],'commercial':'契約モデル','commercial_intro':'料金はカテゴリーの複雑性、候補社数、出張、検査深度、取引構造により異なります。','models':[('固定プロジェクト費','候補選定、比較、サンプル、単発出荷など範囲が明確な案件向け。'),('購買サービス費','発注からQC、集約、輸出まで継続管理する案件向け。'),('月次中国デスク','継続的なRFQ、仕入先フォロー、中国現地調整が必要な企業向け。')],'cta':'案件を相談する →'},
 'about_page':{'title':'Pomerol Internationalについて｜珠海の中国調達実行チーム','desc':'広東省珠海を拠点に、海外バイヤー向け中国サプライヤー開拓、購買、品質管理、OEM/ODM、輸出調整を提供します。','eyebrow':'会社情報','h1':'海外バイヤーのための中国側調達実行パートナー。','intro':'Pomerol Internationalは広東省珠海を拠点としています。工場リンクを転送するだけではなく、要件、見積、サンプル、品質ゲート、出荷書類を意思決定可能な調達プロセスに整理します。','principles_title':'私たちの進め方','principles':[('要件を先に固定','仕様、版数、数量、市場、受入基準を明確にしてから探索範囲を広げます。'),('口約束より証拠','法人、能力、認証、サンプル、試験、検査、書類を確認可能な記録として残します。'),('差異を見える化','価格だけでなくMOQ、金型、材料、包装、納期、除外条件を同時に比較します。'),('出荷準備まで管理','製造完了ではなく、検査、集約、書類、包装、フォワーダー引渡しまで管理します。')],'location_title':'珠海・広東・中国','location':'珠海は粤港澳大湾区に位置し、珠江デルタの製造集積地へのアクセスがあります。案件に応じて広東省および中国各地の産業集積地を対象に調達を進めます。','transparency':'事例の顧客名や一部商業情報は仮名・例示です。写真は関連する実在カテゴリーや調達環境を示すもので、仮名顧客の実出荷証明ではありません。'},
 'resources_page':{'title':'中国調達テンプレート・バイヤーツール｜Pomerol International','desc':'RFQ、サプライヤー比較、工場監査、サンプル承認、出荷前検品、包装、PO、着地原価の実務テンプレートを無料提供。','eyebrow':'バイヤーツールキット','h1':'中国調達を管理するための8つの実務テンプレート。','intro':'チャットやスクリーンショットに散らばった情報を、比較・承認可能な記録へ変えるためのテンプレートです。','toolkit':'調達管理テンプレート','guides':'調達ガイド','guides_desc':'サプライヤー確認、RFQ、サンプル承認、検品、混載、OEM/ODM、調達コストの詳細ガイドも利用できます。'},
 'contact_page':{'title':'Pomerol Internationalへ連絡｜中国調達RFQを開始','desc':'Yusufへ製品、図面、BOM、数量、市場、スケジュールを送り、中国サプライヤー開拓、OEM/ODM、品質・輸出対応を開始。','eyebrow':'RFQを開始','h1':'今ある資料をそのまま送ってください。完璧な整理は不要です。','intro':'商品URL、写真、図面、BOM、過去見積、サンプル問題、候補工場リストのいずれからでも開始できます。','prep':'あると役立つ情報','prep_items':['製品カテゴリーと主要仕様','予定数量、目標価格または予算（あれば）','販売先市場と認証・規制要件','サンプル、量産、出荷の希望時期'],'form_title':'調達ブリーフ','name':'氏名','company':'会社名','email':'メール','market':'国 / 市場','product':'製品 / カテゴリー','quantity':'予定数量','timing':'希望時期','message':'補足','submit':'メールを作成してYusufへ送る →'}
},
'ru': {
 'brand_sub':'Закупки и сорсинг в Китае','services':'Услуги','cases':'Кейсы','about':'О компании','resources':'Материалы','contact':'Начать RFQ','direct':'Прямой контакт',
 'services_page':{'title':'Сорсинг и закупки в Китае | OEM/ODM, контроль качества и экспорт | Pomerol International','desc':'Услуги для зарубежных покупателей: подготовка требований, поиск поставщиков, RFQ, OEM/ODM, образцы, проверка фабрик, инспекция, консолидация и экспорт.','eyebrow':'Закупки в Китае','h1':'От «найдите фабрику» до готового к заказу, проверке и отгрузке проекта.','intro':'Можно использовать отдельный модуль или передать нам функции китайского закупочного офиса. До начала фиксируем объем работ, ответственность, коммерческие условия и сторонние расходы.','modules_title':'Восемь блоков — один контролируемый процесс.','modules_intro':'Поиск, техническая проверка, образцы, качество и логистика разделены, чтобы стоимость, риски и ответственность оставались видимыми.','modules':[('Формализация требований','Превращаем фото, чертежи, BOM, ссылки или первоначальную идею в рабочее техническое задание для RFQ.'),('Поиск и отбор поставщиков','Ищем по производственным кластерам, B2B-площадкам и отраслевым каналам, заранее отсеивая несоответствия.'),('Нормализация RFQ','Сравниваем оснастку, MOQ, цену, упаковку, оплату, сроки, гарантию и исключения на одной базе.'),('Образцы и DFM','Ведем версии образцов, техническую обратную связь и отклонения до разрешения серийного производства.'),('Квалификация поставщика','Проверяем юридическое лицо, производственные доказательства, сертификаты и процессные возможности.'),('Контроль качества','Определяем проверки по чертежам, утвержденному образцу, AQL или критериям проекта.'),('Консолидация и экспорт','Координируем поставки от нескольких фабрик, упаковочные листы, маркировку, коммерческие документы и передачу экспедитору.'),('Постоянный закупочный офис','Для регулярных RFQ, повторных заказов, альтернативных поставщиков и обработки исключений.')],'commercial':'Модели работы','commercial_intro':'Точная стоимость зависит от сложности категории, числа поставщиков, поездок, глубины контроля и структуры сделки.','models':[('Фиксированный проект','Для четко ограниченной задачи: shortlist, сравнение, образцы или одна отгрузка.'),('Закупочный сервис','Когда мы ведем исполнение заказа, QC, консолидацию и экспорт.'),('Ежемесячный China desk','Для компаний с регулярными RFQ и постоянной координацией в Китае.')],'cta':'Обсудить проект →'},
 'about_page':{'title':'О Pomerol International | Команда по закупкам в Чжухае, Китай','desc':'Pomerol International находится в Чжухае, провинция Гуандун, и помогает зарубежным покупателям с поставщиками, закупками, OEM/ODM, качеством и экспортом.','eyebrow':'О компании','h1':'Китайская сторона исполнения для зарубежного покупателя.','intro':'Pomerol International базируется в Чжухае, провинция Гуандун. Мы не ограничиваемся списком фабрик: требования, котировки, образцы, контрольные точки качества и отгрузочные документы превращаются в управляемый процесс закупки.','principles_title':'Как мы работаем','principles':[('Сначала требования','Фиксируем спецификацию, ревизию, количество, рынок и приемочные критерии до расширения поиска.'),('Доказательства вместо обещаний','Юридические данные, возможности, сертификаты, образцы, испытания, инспекции и документы должны быть проверяемыми.'),('Отклонения видимы','Сравниваем не только цену, но и MOQ, оснастку, материалы, упаковку, сроки и исключения.'),('Работа заканчивается не на фабрике','Контролируем инспекцию, консолидацию, документы, упаковку и передачу экспедитору.')],'location_title':'Чжухай · Гуандун · Китай','location':'Чжухай расположен в Greater Bay Area и связан с производственными кластерами дельты Жемчужной реки. По проекту поиск может охватывать Гуандун и другие профильные кластеры Китая.','transparency':'Имена клиентов и часть коммерческих деталей в кейсах являются псевдонимами или иллюстративными данными. Фотографии показывают реальные категории продукции и среды, но не являются доказательством отгрузки конкретному псевдонимному клиенту.'},
 'resources_page':{'title':'Шаблоны для закупок в Китае | Pomerol International','desc':'Практические шаблоны RFQ, оценки поставщиков, аудита фабрики, утверждения образца, PSI, упаковки, PO и расчета landed cost.','eyebrow':'Инструменты покупателя','h1':'Восемь рабочих файлов для контроля закупки в Китае.','intro':'Шаблоны переводят сведения из чатов и скриншотов в записи, которые можно сравнивать, утверждать и проверять.','toolkit':'Шаблоны контроля закупок','guides':'Гайды для покупателей','guides_desc':'Подробные материалы о проверке поставщиков, RFQ, образцах, инспекции, консолидации, OEM/ODM и стоимости закупки.'},
 'contact_page':{'title':'Связаться с Pomerol International | Начать RFQ по Китаю','desc':'Отправьте Yusuf информацию о продукте, чертежи, BOM, количество, рынок и сроки для начала поиска поставщиков, OEM/ODM, контроля и экспорта.','eyebrow':'Начать RFQ','h1':'Отправьте то, что уже есть — идеальная подготовка не нужна.','intro':'Ссылка на продукт, фотографии, чертежи, BOM, старые котировки, проблемы образца или список поставщиков — любой из этих материалов подходит для старта.','prep':'Что желательно указать','prep_items':['Продукт/категория и ключевые требования','Количество и целевая цена/бюджет, если есть','Рынок назначения и требования сертификации','Желаемые сроки образца, производства или отгрузки'],'form_title':'Закупочный бриф','name':'Имя','company':'Компания','email':'Email','market':'Страна / рынок','product':'Продукт / категория','quantity':'Количество','timing':'Сроки','message':'Дополнительная информация','submit':'Создать письмо Yusuf →'}
},
'es': {
 'brand_sub':'Sourcing y compras en China','services':'Servicios','cases':'Casos','about':'Empresa','resources':'Recursos','contact':'Iniciar RFQ','direct':'Contacto directo',
 'services_page':{'title':'Servicios de sourcing en China | OEM/ODM, inspección y exportación | Pomerol International','desc':'Ejecución de compras en China para compradores internacionales: requisitos, proveedores, RFQ, OEM/ODM, muestras, auditoría, inspección, consolidación y exportación.','eyebrow':'Servicios de sourcing en China','h1':'De “encuéntrame una fábrica” a una compra lista para aprobar, inspeccionar y enviar.','intro':'Puede contratar un módulo o utilizar Pomerol como mesa de compras en China. Antes de comenzar definimos alcance, responsabilidades, condiciones comerciales y costes de terceros.','modules_title':'Ocho módulos, un flujo de compras controlable.','modules_intro':'Separamos sourcing, validación técnica, muestras, calidad y logística para mantener visibles costes, riesgos y responsabilidades.','modules':[('Ingeniería de requisitos','Convertimos fotos, planos, BOM, enlaces o ideas preliminares en un brief utilizable para RFQ.'),('Búsqueda y filtrado de proveedores','Buscamos en clusters industriales, plataformas B2B y fuentes especializadas, descartando pronto las incompatibilidades.'),('Normalización de RFQ','Comparamos tooling, MOQ, precio, embalaje, pago, plazo, garantía y exclusiones sobre la misma base.'),('Muestras y seguimiento DFM','Controlamos revisiones de muestra, feedback técnico y desviaciones antes de liberar producción.'),('Calificación de proveedores','Revisamos identidad legal, evidencia de fábrica, certificaciones y capacidad de proceso.'),('Control de calidad','Definimos controles según planos, muestra aprobada, AQL o criterios específicos del proyecto.'),('Consolidación y documentos','Coordinamos entregas de varios proveedores, packing lists, marcas, documentos comerciales y entrega al transitario.'),('Mesa de compras recurrentes','Gestionamos RFQ recurrentes, reposiciones, alternativas y excepciones desde China.')],'commercial':'Modelos comerciales','commercial_intro':'Las tarifas dependen de complejidad, número de proveedores, viajes, profundidad de inspección y estructura de la operación.','models':[('Tarifa fija de proyecto','Para misiones definidas: shortlist, comparación, muestras o un envío.'),('Tarifa de servicio de compras','Cuando gestionamos ejecución, QC, consolidación y exportación.'),('Mesa mensual en China','Para empresas con RFQ y coordinación local recurrentes.')],'cta':'Hablar del proyecto →'},
 'about_page':{'title':'Sobre Pomerol International | Equipo de sourcing en Zhuhai, China','desc':'Pomerol International opera desde Zhuhai, Guangdong, apoyando a compradores internacionales con proveedores, compras, OEM/ODM, calidad y exportación.','eyebrow':'Sobre nosotros','h1':'Ejecución de compras en China para compradores internacionales.','intro':'Pomerol International tiene base en Zhuhai, Guangdong. No nos limitamos a reenviar enlaces de fábricas: estructuramos requisitos, ofertas, muestras, puntos de control de calidad y documentación de entrega para que el comprador pueda decidir y seguir el proyecto.','principles_title':'Cómo trabajamos','principles':[('Primero los requisitos','Definimos especificación, revisión, cantidad, mercado y criterios de aceptación antes de ampliar la búsqueda.'),('Evidencia antes que promesas','Identidad, capacidad, certificaciones, muestras, pruebas, inspecciones y documentos deben poder revisarse.'),('Desviaciones visibles','El precio no se compara solo: MOQ, tooling, materiales, embalaje, plazo y exclusiones deben quedar claros.'),('La entrega va más allá de producción','Seguimos inspección, consolidación, documentos, embalaje y transferencia al transitario.')],'location_title':'Zhuhai · Guangdong · China','location':'Zhuhai forma parte de la Greater Bay Area y conecta con los clusters manufactureros del Delta del Río Perla. Según la categoría trabajamos también con otros clusters industriales de China.','transparency':'Los nombres de clientes y determinados detalles comerciales de los casos son seudónimos o ilustrativos. Las fotografías representan categorías y entornos reales, pero no prueban un envío a un cliente seudónimo concreto.'},
 'resources_page':{'title':'Plantillas de compras y sourcing en China | Pomerol International','desc':'Descargue plantillas prácticas de RFQ, evaluación de proveedores, auditoría, aprobación de muestras, inspección, embalaje, PO y landed cost.','eyebrow':'Toolkit del comprador','h1':'Ocho archivos prácticos para controlar una compra en China.','intro':'Las plantillas convierten información dispersa en chats y capturas en registros comparables, aprobables y auditables.','toolkit':'Plantillas de control de compras','guides':'Guías de sourcing','guides_desc':'Guías detalladas sobre verificación de proveedores, RFQ, muestras, inspección, consolidación, OEM/ODM y costes de sourcing.'},
 'contact_page':{'title':'Contactar Pomerol International | Iniciar RFQ en China','desc':'Envíe a Yusuf producto, planos, BOM, cantidad, mercado y plazos para iniciar búsqueda de proveedores, OEM/ODM, calidad y exportación desde China.','eyebrow':'Iniciar RFQ','h1':'Envíe lo que ya tiene; no necesita preparar un expediente perfecto.','intro':'Un enlace de producto, fotos, planos, BOM, ofertas anteriores, problemas de muestra o lista de proveedores pueden ser el punto de partida.','prep':'Información útil','prep_items':['Producto/categoría y especificaciones clave','Cantidad estimada y precio objetivo o presupuesto si existe','Mercado destino y requisitos de certificación','Plazo deseado para muestra, producción o envío'],'form_title':'Brief de compras','name':'Nombre','company':'Empresa','email':'Email','market':'País / mercado','product':'Producto / categoría','quantity':'Cantidad estimada','timing':'Plazo objetivo','message':'Información adicional','submit':'Crear email para Yusuf →'}
},
'pt': {
 'brand_sub':'Sourcing e compras na China','services':'Serviços','cases':'Casos','about':'Empresa','resources':'Recursos','contact':'Iniciar RFQ','direct':'Contato direto',
 'services_page':{'title':'Serviços de sourcing na China | OEM/ODM, inspeção e exportação | Pomerol International','desc':'Execução de compras na China para compradores internacionais: requisitos, fornecedores, RFQ, OEM/ODM, amostras, auditoria, inspeção, consolidação e exportação.','eyebrow':'Serviços de sourcing na China','h1':'De “encontre uma fábrica” a uma compra pronta para aprovar, inspecionar e embarcar.','intro':'Use um módulo específico ou a Pomerol como mesa de compras na China. Antes do início definimos escopo, responsabilidades, condições comerciais e custos de terceiros.','modules_title':'Oito módulos, um fluxo de compras controlável.','modules_intro':'Separamos sourcing, validação técnica, amostras, qualidade e logística para manter custos, riscos e responsabilidades visíveis.','modules':[('Engenharia de requisitos','Transformamos fotos, desenhos, BOM, links ou ideias iniciais em um briefing utilizável para RFQ.'),('Busca e triagem de fornecedores','Pesquisamos clusters industriais, plataformas B2B e fontes especializadas, eliminando incompatibilidades cedo.'),('Normalização de RFQ','Comparamos tooling, MOQ, preço, embalagem, pagamento, prazo, garantia e exclusões na mesma base.'),('Amostras e DFM','Controlamos revisões de amostra, feedback técnico e desvios antes da liberação da produção.'),('Qualificação de fornecedor','Revisamos identidade legal, evidências da fábrica, certificações e capacidade de processo.'),('Controle de qualidade','Definimos pontos de controle por desenho, amostra aprovada, AQL ou critérios do projeto.'),('Consolidação e documentos','Coordenamos entregas de vários fornecedores, packing lists, marcas, documentos comerciais e entrega ao agente de carga.'),('Mesa recorrente de compras','Gerimos RFQs recorrentes, reposição, alternativas e exceções a partir da China.')],'commercial':'Modelos comerciais','commercial_intro':'As tarifas dependem da complexidade, número de fornecedores, viagens, profundidade de inspeção e estrutura da operação.','models':[('Taxa fixa de projeto','Para missões definidas: shortlist, comparação, amostras ou um embarque.'),('Taxa de serviço de compras','Quando gerimos execução, QC, consolidação e exportação.'),('Mesa mensal na China','Para empresas com RFQs e coordenação local recorrentes.')],'cta':'Discutir o projeto →'},
 'about_page':{'title':'Sobre a Pomerol International | Equipe de sourcing em Zhuhai, China','desc':'A Pomerol International opera em Zhuhai, Guangdong, apoiando compradores internacionais com fornecedores, compras, OEM/ODM, qualidade e exportação.','eyebrow':'Sobre nós','h1':'Execução de compras na China para compradores internacionais.','intro':'A Pomerol International está baseada em Zhuhai, Guangdong. Não apenas encaminhamos links de fábricas: organizamos requisitos, cotações, amostras, gates de qualidade e documentação de entrega em um processo de compra rastreável.','principles_title':'Como trabalhamos','principles':[('Requisitos primeiro','Definimos especificação, revisão, quantidade, mercado e critérios de aceitação antes de ampliar a busca.'),('Evidência antes de promessa','Identidade, capacidade, certificações, amostras, testes, inspeções e documentos devem ser verificáveis.'),('Desvios visíveis','Preço não é comparado sozinho: MOQ, tooling, material, embalagem, prazo e exclusões precisam estar claros.'),('Entrega vai além da produção','Acompanhamos inspeção, consolidação, documentos, embalagem e transferência ao agente de carga.')],'location_title':'Zhuhai · Guangdong · China','location':'Zhuhai integra a Greater Bay Area e conecta-se aos clusters industriais do Delta do Rio das Pérolas. Dependendo da categoria, trabalhamos também com outros clusters produtivos na China.','transparency':'Os nomes de clientes e alguns detalhes comerciais dos casos são pseudônimos ou ilustrativos. As fotografias mostram categorias e ambientes reais, mas não comprovam embarque para um cliente pseudônimo específico.'},
 'resources_page':{'title':'Modelos de compras e sourcing na China | Pomerol International','desc':'Baixe modelos práticos de RFQ, avaliação de fornecedores, auditoria, aprovação de amostras, inspeção, embalagem, PO e landed cost.','eyebrow':'Toolkit do comprador','h1':'Oito arquivos práticos para controlar uma compra na China.','intro':'Os modelos transformam informações dispersas em chats e capturas em registros comparáveis, aprováveis e auditáveis.','toolkit':'Modelos de controle de compras','guides':'Guias de sourcing','guides_desc':'Guias detalhados sobre verificação de fornecedores, RFQ, amostras, inspeção, consolidação, OEM/ODM e custos de sourcing.'},
 'contact_page':{'title':'Contatar Pomerol International | Iniciar RFQ na China','desc':'Envie a Yusuf produto, desenhos, BOM, quantidade, mercado e prazo para iniciar busca de fornecedores, OEM/ODM, qualidade e exportação na China.','eyebrow':'Iniciar RFQ','h1':'Envie o que você já tem; não precisa preparar um dossiê perfeito.','intro':'Link de produto, fotos, desenhos, BOM, cotações antigas, problema de amostra ou lista de fornecedores podem ser o ponto de partida.','prep':'Informações úteis','prep_items':['Produto/categoria e especificações principais','Quantidade estimada e preço-alvo ou orçamento se houver','Mercado de destino e requisitos de certificação','Prazo desejado para amostra, produção ou embarque'],'form_title':'Briefing de compras','name':'Nome','company':'Empresa','email':'Email','market':'País / mercado','product':'Produto / categoria','quantity':'Quantidade estimada','timing':'Prazo desejado','message':'Informações adicionais','submit':'Criar email para Yusuf →'}
}
}

FILES = [
 ('rfq-template.csv','RFQ requirement template'),('supplier-scorecard.csv','Supplier comparison scorecard'),('supplier-audit-checklist.csv','Supplier audit checklist'),('sample-approval-sheet.csv','Sample approval sheet'),('pre-shipment-inspection-checklist.csv','Pre-shipment inspection checklist'),('packaging-specification-template.csv','Packaging specification template'),('purchase-order-checklist.csv','Purchase order checklist'),('landed-cost-calculator.csv','Landed-cost calculator')
]

def e(v): return html.escape(str(v), quote=True)

def alts(page):
    d={'en':f'/{page}/'}
    for code in LOCALES: d[LANG[code]]=f'/{code}/{page}/'
    d['x-default']=f'/{page}/'
    return d

def nav(code,c):
    return f'<header class="nav-shell"><nav class="nav wrap"><a class="brand" href="/{code}/"><img src="/assets/logo.svg" alt="Pomerol International"><span>Pomerol International<small>{e(c["brand_sub"])}</small></span></a><button class="menu-btn" data-menu aria-label="Menu">☰</button><div class="navlinks" data-nav><a href="/{code}/services/">{e(c["services"])}</a><a href="/{code}/cases/">{e(c["cases"])}</a><a href="/{code}/about/">{e(c["about"])}</a><a href="/{code}/resources/">{e(c["resources"])}</a><a class="nav-cta" href="/{code}/contact/">{e(c["contact"])}</a></div></nav></header>'

def footer(code,c):
    return f'<footer class="footer"><div class="wrap"><div class="footer-grid"><div><a class="brand" href="/{code}/"><img src="/assets/logo.svg" alt=""><span>Pomerol International<small>波美猴国际贸易（珠海）有限公司</small></span></a><p style="max-width:380px;color:#aebccd">China sourcing, procurement, OEM/ODM, quality control and export coordination.</p></div><div><h4>{e(c["services"])}</h4><a href="/{code}/services/">{e(c["services"])}</a><a href="/{code}/cases/">{e(c["cases"])}</a><a href="/{code}/about/">{e(c["about"])}</a></div><div><h4>{e(c["resources"])}</h4><a href="/{code}/resources/">{e(c["resources"])}</a><a href="/{code}/resources/guides/">Buyer Guides</a><a href="/sitemap/">Site directory</a></div><div><h4>{e(c["direct"])}</h4><a href="tel:+8613242694270">+86 132 4269 4270</a><a href="mailto:abd.yusuf.ibrahim.mustafa@gmail.com">abd.yusuf.ibrahim.mustafa@gmail.com</a><a href="https://wa.me/8613242694270">WhatsApp</a></div></div><div class="footer-bottom"><span>© 2026 Pomerol International Trade (Zhuhai) Co., Ltd.</span><span><a style="display:inline" href="/privacy/">Privacy</a> · <a style="display:inline" href="/terms/">Terms</a></span></div></div></footer>'

def page(code,kind,title,desc,body,img):
    can=f'{BASE}/{code}/{kind}/'; tags=seo.seo_tags(title,desc,can,LANG[code],BASE+img,alts=alts(kind),extra=[seo.crumbs(can,title)])
    c=COPY[code]
    return f'<!doctype html><html lang="{LANG[code]}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)}</title><meta name="description" content="{e(desc)}"><link rel="icon" href="/assets/logo.svg"><link rel="stylesheet" href="/assets/site.css"><script defer src="/assets/site.js"></script>{tags}</head><body>{nav(code,c)}<main>{body}</main>{footer(code,c)}</body></html>'

def services_body(code):
    d=COPY[code]['services_page']; modules=''.join(f'<div class="service-row"><div class="n">{i:02d}</div><div><h3>{e(t)}</h3><p>{e(x)}</p></div></div>' for i,(t,x) in enumerate(d['modules'],1)); models=''.join(f'<article class="card"><h3>{e(t)}</h3><p>{e(x)}</p></article>' for t,x in d['models'])
    return f'<section class="page-hero"><div class="wrap page-hero-grid"><div><div class="eyebrow">{e(d["eyebrow"])}</div><h1 class="display">{e(d["h1"])}</h1><p>{e(d["intro"])}</p><div class="hero-actions"><a class="btn primary" href="/{code}/contact/">{e(d["cta"])}</a><a class="btn light" href="/{code}/cases/">{e(COPY[code]["cases"])}</a></div></div><div><img src="/assets/photos/product-development.jpg" alt="China sourcing and product development"></div></div></section><section class="section"><div class="wrap detail-grid"><aside class="sticky"><div class="eyebrow">{e(d["eyebrow"])}</div><h2 class="display">{e(d["modules_title"])}</h2><p>{e(d["modules_intro"])}</p></aside><div>{modules}</div></div></section><section class="section dark"><div class="wrap"><div class="section-head"><div><div class="eyebrow">{e(d["commercial"])}</div><h2 class="display">{e(d["commercial"])}</h2></div><p class="muted">{e(d["commercial_intro"])}</p></div><div class="grid-3">{models}</div></div></section>'

def about_body(code):
    d=COPY[code]['about_page']; cards=''.join(f'<article class="card"><h3>{e(t)}</h3><p>{e(x)}</p></article>' for t,x in d['principles'])
    return f'<section class="page-hero"><div class="wrap page-hero-grid"><div><div class="eyebrow">{e(d["eyebrow"])}</div><h1 class="display">{e(d["h1"])}</h1><p>{e(d["intro"])}</p></div><div><img src="/assets/photos/product-development.jpg" alt="Pomerol International China sourcing team context"></div></div></section><section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Pomerol International</div><h2 class="display">{e(d["principles_title"])}</h2></div></div><div class="grid-2">{cards}</div></div></section><section class="section dark"><div class="wrap split"><div><div class="eyebrow">China base</div><h2 class="display">{e(d["location_title"])}</h2><p class="lead">{e(d["location"])}</p></div><div class="notice-box">{e(d["transparency"])}</div></div></section>'

def resources_body(code):
    d=COPY[code]['resources_page']; items=''.join(f'<div class="resource"><div><strong>{e(label)}</strong><span>CSV working template</span></div><a class="small-link" href="/resources/{e(fn)}" download>Download CSV →</a></div>' for fn,label in FILES)
    return f'<section class="page-hero"><div class="wrap page-hero-grid"><div><div class="eyebrow">{e(d["eyebrow"])}</div><h1 class="display">{e(d["h1"])}</h1><p>{e(d["intro"])}</p></div><div><img src="/assets/photos/precision-machining.jpg" alt="China sourcing procurement toolkit"></div></div></section><section class="section"><div class="wrap split"><div><div class="eyebrow">{e(d["toolkit"])}</div><h2 class="display">{e(d["toolkit"])}</h2><p class="lead">RFQ → supplier → sample → QC → PO → landed cost.</p><a class="btn light" href="/{code}/resources/guides/">{e(d["guides"])}</a><p>{e(d["guides_desc"])}</p></div><div>{items}</div></div></section>'

def contact_body(code):
    d=COPY[code]['contact_page']; prep=''.join(f'<li>{e(x)}</li>' for x in d['prep_items'])
    return f'<section class="page-hero"><div class="wrap page-hero-grid"><div><div class="eyebrow">{e(d["eyebrow"])}</div><h1 class="display">{e(d["h1"])}</h1><p>{e(d["intro"])}</p><div class="hero-actions"><a class="btn primary" href="https://wa.me/8613242694270">WhatsApp →</a><a class="btn light" href="mailto:abd.yusuf.ibrahim.mustafa@gmail.com">Email Yusuf</a></div></div><div><img src="/assets/photos/product-development.jpg" alt="Start a China sourcing RFQ"></div></div></section><section class="section"><div class="wrap split"><div><div class="eyebrow">{e(d["prep"])}</div><h2 class="display">{e(d["prep"])}</h2><ul>{prep}</ul><div class="notice-box">Yusuf · +86 132 4269 4270 · abd.yusuf.ibrahim.mustafa@gmail.com</div></div><form class="card" data-inquiry-form><h3>{e(d["form_title"])}</h3><label>{e(d["name"])}<input name="name" autocomplete="name"></label><label>{e(d["company"])}<input name="company" autocomplete="organization"></label><label>{e(d["email"])}<input name="email" type="email" autocomplete="email"></label><label>{e(d["market"])}<input name="market"></label><label>{e(d["product"])}<input name="product"></label><label>{e(d["quantity"])}<input name="quantity"></label><label>{e(d["timing"])}<input name="timing"></label><label>{e(d["message"])}<textarea name="message" rows="6"></textarea></label><button class="btn primary" type="submit">{e(d["submit"])}</button></form></div></section>'

def write_pages():
    made=0
    for code in LOCALES:
        c=COPY[code]
        specs=[('services',c['services_page'],services_body(code),'/assets/photos/product-development.jpg'),('about',c['about_page'],about_body(code),'/assets/photos/product-development.jpg'),('resources',c['resources_page'],resources_body(code),'/assets/photos/precision-machining.jpg'),('contact',c['contact_page'],contact_body(code),'/assets/photos/product-development.jpg')]
        for kind,d,body,img in specs:
            out=PUBLIC/code/kind; out.mkdir(parents=True,exist_ok=True); (out/'index.html').write_text(page(code,kind,d['title'],d['desc'],body,img),encoding='utf-8'); made+=1
    return made

def patch_english_clusters():
    for kind in ('services','about','resources','contact'):
        p=PUBLIC/kind/'index.html'; text=p.read_text(encoding='utf-8'); title,desc=seo.title_desc(text); text=seo.strip_seo(text); can=f'{BASE}/{kind}/'; img=seo.image_for(text); tags=seo.seo_tags(title,desc,can,'en',img,alts=alts(kind),extra=[seo.crumbs(can,title)]); text=text.replace('</head>',tags+'\n</head>',1); p.write_text(text,encoding='utf-8')

def patch_local_internal_links():
    for code in LOCALES:
        for p in (PUBLIC/code).rglob('*.html'):
            text=p.read_text(encoding='utf-8')
            for kind in ('services','about','resources','contact'):
                text=text.replace(f'href="/{kind}/"',f'href="/{code}/{kind}/"')
            p.write_text(text,encoding='utf-8')

def main():
    made=write_pages(); assert made==20,made
    patch_english_clusters(); patch_local_internal_links()
    for kind in ('services','about','resources','contact'):
        en=(PUBLIC/kind/'index.html').read_text(encoding='utf-8')
        for code in LOCALES:
            assert f'hreflang="{LANG[code]}" href="{BASE}/{code}/{kind}/"' in en,(kind,code)
            p=PUBLIC/code/kind/'index.html'; assert p.is_file(),p; t=p.read_text(encoding='utf-8'); assert 'hreflang="en"' in t and f'rel="canonical" href="{BASE}/{code}/{kind}/"' in t,p
    print('Localized deep pages OK: 20 pages + 4 reciprocal six-language hreflang clusters')

if __name__=='__main__': main()
